/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Ventanas;

import CapturaPaquetes.PacketContents;
import CapturaPaquetes.jpcap_thread;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import jpcap.JpcapCaptor;
import jpcap.JpcapWriter;
import jpcap.NetworkInterface;
import jpcap.packet.Packet;


/**
 *
 * @author adrian
 */
public class AnalizadorPaquetes extends javax.swing.JFrame {
    
    public static NetworkInterface[] NETWORK_INTERFACES;
    public static JpcapCaptor CAP;
    jpcap_thread THREAD;
    public static int INDEX;
    public static int flag;
    public static int COUNTER;
    boolean CaptureState;
    public static int No;
    private final JFrame ventanaInicio;
    
    JpcapWriter writer = null;
    List<Packet> packetList;

    /**
     * Creates new form AnalizadorMensajes
     * @param ventanaInicio
     */
    public AnalizadorPaquetes(JFrame ventanaInicio) {
        initComponents();
        
        writer = null;
        packetList = new ArrayList<>();
        INDEX = 1; //interface        
        flag = 0;
        COUNTER = 1;
        CaptureState = false;
        No = 1;
        NETWORK_INTERFACES = JpcapCaptor.getDeviceList();
        
        this.ventanaInicio = ventanaInicio;        
        NETWORK_INTERFACES =JpcapCaptor.getDeviceList(); 
        int numeroDispositivo = -1;
        for (NetworkInterface dispositivo : NETWORK_INTERFACES) {
            numeroDispositivo+=1;
            this.jComboBoxInterfaces.addItem(numeroDispositivo+". "+dispositivo.description
                    +"-"+dispositivo.datalink_name+ "-" + dispositivo.datalink_description);            
        }       
    }
    
    public void CapturePackets() {

        THREAD = new jpcap_thread() {
            
            @Override
            public Object construct() {

                try {

                    CAP = JpcapCaptor.openDevice(NETWORK_INTERFACES[INDEX], 65535, false, 1000);
                    
                    while (CaptureState) {
                        
                        CAP.processPacket(1, new PacketContents());
                        packetList.add(CAP.getPacket());
                    }
                    CAP.close();

                } catch (IOException e) {
                    System.out.print(e);
                }
                return 0;
            }

            @Override
            public void finished() {
                this.interrupt();
            }
        };

        THREAD.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonCapturar = new javax.swing.JButton();
        jButtonDetener = new javax.swing.JButton();
        jComboBoxInterfaces = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonRegresar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDetalles = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablePaquetes = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Captura de mensajes");

        jButtonCapturar.setText("Empezar captura");
        jButtonCapturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCapturarActionPerformed(evt);
            }
        });

        jButtonDetener.setText("Detener captura");
        jButtonDetener.setEnabled(false);
        jButtonDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetenerActionPerformed(evt);
            }
        });

        jLabel2.setText("Interfaces:");

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jTextAreaDetalles.setColumns(20);
        jTextAreaDetalles.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextAreaDetalles.setRows(5);
        jTextAreaDetalles.setEnabled(false);
        jScrollPane2.setViewportView(jTextAreaDetalles);

        jTablePaquetes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTablePaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Length", "Source", "Destination", "Protocol", "Length"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTablePaquetes.setRowHeight(20);
        jTablePaquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePaquetesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTablePaquetes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRegresar)
                .addGap(328, 328, 328)
                .addComponent(jButtonSalir)
                .addGap(282, 282, 282))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addComponent(jComboBoxInterfaces, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jButtonCapturar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDetener))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonCapturar)
                    .addComponent(jButtonDetener)
                    .addComponent(jComboBoxInterfaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegresar)
                    .addComponent(jButtonSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCapturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCapturarActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTablePaquetes.getModel();
        model.setRowCount(0);
        No = 1;
        PacketContents.rowList.clear();
        jTextAreaDetalles.setText("");
        
        jButtonCapturar.setEnabled(false);
        jButtonDetener.setEnabled(true);
        jComboBoxInterfaces.setEnabled(false);
        
        String datosInterface = (String)jComboBoxInterfaces.getSelectedItem();         
        int pointIndex = datosInterface.indexOf(".");           
        int idInterface = Integer.parseInt(datosInterface.substring(0, pointIndex));
        //System.out.println(idInterface);      
        
        INDEX = idInterface;
        
        CaptureState = true;
        CapturePackets();       
    }//GEN-LAST:event_jButtonCapturarActionPerformed

    private void jButtonDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetenerActionPerformed
        CaptureState = false;
        THREAD.finished();      
        jButtonCapturar.setEnabled(true);
        jButtonDetener.setEnabled(false);
        jComboBoxInterfaces.setEnabled(true);
    }//GEN-LAST:event_jButtonDetenerActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        this.dispose();
        this.ventanaInicio.setVisible(true);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTablePaquetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePaquetesMouseClicked
        jTextAreaDetalles.setText("");        
        Object obj = jTablePaquetes.getModel().getValueAt(jTablePaquetes.getSelectedRow(), 0);
        int nPaquete = (int) obj;
        nPaquete -=1;
        
        if (PacketContents.rowList.get(nPaquete)[4] == "TCP") {
            
            jTextAreaDetalles.setText("Packet No: " + PacketContents.rowList.get(nPaquete)[0]
                    + "\nSeq No: " + PacketContents.rowList.get(nPaquete)[10]
                    + "\nProtocol: " + PacketContents.rowList.get(nPaquete)[4]
                    + "\nSource IP: " + PacketContents.rowList.get(nPaquete)[2]
                    + "\nDist IP: " + PacketContents.rowList.get(nPaquete)[3]
                    + "\nLength: " + PacketContents.rowList.get(nPaquete)[1]
                    + "\nSource Port: " + PacketContents.rowList.get(nPaquete)[5]
                    + "\nDist Port: " + PacketContents.rowList.get(nPaquete)[6]
                    + "\nAck: " + PacketContents.rowList.get(nPaquete)[7]
                    + "\nAck No: " + PacketContents.rowList.get(nPaquete)[8]
                    + "\nSequence No: " + PacketContents.rowList.get(nPaquete)[10]
                    //+ "\nOffset: " + PacketContents.rowList.get((int) obj)[11]
                    + "\nHeader: " + PacketContents.rowList.get(nPaquete)[12]
                    + "\nData: " + PacketContents.rowList.get(nPaquete)[9]
            );
            /*
            try {
                jTextArea2.setText(customizeHexa(toHexadecimal(jTextAreaDetalles.getText())));
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(sniffer.class.getName()).log(Level.SEVERE, null, ex);
            }*/

        } else if (PacketContents.rowList.get(nPaquete)[4] == "UDP") {
            jTextAreaDetalles.setText("Packet No: " + PacketContents.rowList.get(nPaquete)[0]
                    + "\nProtocol:" + PacketContents.rowList.get(nPaquete)[4]
                    + "\nSource IP: " + PacketContents.rowList.get(nPaquete)[2]
                    + "\nDist IP: " + PacketContents.rowList.get(nPaquete)[3]
                    + "\nLength: " + PacketContents.rowList.get(nPaquete)[1]
                    + "\nSource Port: " + PacketContents.rowList.get(nPaquete)[5]
                    + "\nDist Port: " + PacketContents.rowList.get(nPaquete)[6]
                    + "\nOffset: " + PacketContents.rowList.get(nPaquete)[8]
                    + "\nHeader: " + PacketContents.rowList.get(nPaquete)[9]
                    + "\nData: " + PacketContents.rowList.get(nPaquete)[7]
            );
            /*
            try {
                jTextArea2.setText(customizeHexa(toHexadecimal(jTextAreaDetalles.getText())));
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(sniffer.class.getName()).log(Level.SEVERE, null, ex);
            }*/

        } else if (PacketContents.rowList.get(nPaquete)[4] == "ICMP") {
            jTextAreaDetalles.setText("Packet No: " + PacketContents.rowList.get(nPaquete)[0]
                    + "\nProtocol:" + PacketContents.rowList.get(nPaquete)[4]
                    + "\nSource IP: " + PacketContents.rowList.get(nPaquete)[2]
                    + "\nDist IP: " + PacketContents.rowList.get(nPaquete)[3]
                    + "\nLength: " + PacketContents.rowList.get(nPaquete)[1]
                    + "\nChecksum: " + PacketContents.rowList.get(nPaquete)[5]
                    + "\nHeader: " + PacketContents.rowList.get(nPaquete)[6]
                    + "\nOffset: " + PacketContents.rowList.get(nPaquete)[7]
                    + "\nOriginate TimeStamp: " + PacketContents.rowList.get(nPaquete)[8] + "bits"
                    + "\nRecieve TimeStamp: " + PacketContents.rowList.get(nPaquete)[9] + "bits"
                    + "\nTransmit TimeStamp: " + PacketContents.rowList.get(nPaquete)[10] + "bits"
                    + "\nData: " + PacketContents.rowList.get(nPaquete)[11]
            );
            /*
            try {
                jTextArea2.setText(customizeHexa(toHexadecimal(jTextAreaDetalles.getText())));
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(sniffer.class.getName()).log(Level.SEVERE, null, ex);
            }*/
        }
    }//GEN-LAST:event_jTablePaquetesMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCapturar;
    private javax.swing.JButton jButtonDetener;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxInterfaces;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTable jTablePaquetes;
    private javax.swing.JTextArea jTextAreaDetalles;
    // End of variables declaration//GEN-END:variables
}
