/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Ventanas;

import GUI.Odometro.Gauge.Radial;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import MedicionThroughput.Throughput;

/**
 *
 * @author adrian
 */
public class MedicionThroughput extends javax.swing.JFrame implements ActionListener {

    private final JFrame ventanaInicio;
    private final Radial gaugeRecibido;
    private final Radial gaugeEnviado;
    
    private int contador;
    private long recibidoAntes, enviadoAntes, diferenciaRecibido, diferenciaEnviado;
    private double anchoBanda,throughputEnviado, throughputRecibido;
    private final Throughput test;
    
    /**
     * Creates new form MedicionThroughput
     * @param ventanaInicio
     */
    public MedicionThroughput(JFrame ventanaInicio) {
        
        initComponents();
        this.ventanaInicio = ventanaInicio;
        
        this.test = new Throughput();
        test.run();
        this.anchoBanda = (double)test.getAnchoBanda()/1000000;
        this.jLabelAnchoBanda.setText("Ancho de banda: "+round(this.anchoBanda,2)+" Mbps");
        
        //System.out.println("ancho de banda="+test.getAnchoBanda());
        this.gaugeRecibido= new Radial();
        this.gaugeRecibido.setTitle("Recibido");
        this.gaugeRecibido.setUnitString("Mbps");
        this.gaugeRecibido.setMaxValue(this.anchoBanda);
        this.jPanel1.setLayout(new BorderLayout());
        this.jPanel1.add(this.gaugeRecibido, BorderLayout.CENTER);
        
        this.gaugeEnviado= new Radial();
        this.gaugeEnviado.setTitle("Enviado");
        this.gaugeEnviado.setUnitString("Mbps");
        this.gaugeEnviado.setMaxValue(this.anchoBanda);
        this.jPanel2.setLayout(new BorderLayout());
        this.jPanel2.add(this.gaugeEnviado, BorderLayout.CENTER);
        
        this.pack();      
        
        this.contador = 0;
        this.throughputRecibido = 0;
        this.throughputEnviado = 0;
    }
    
    @Override
    public void actionPerformed(ActionEvent e){
        this.contador++;
        if (this.contador == 1){
            this.test.run();
            this.recibidoAntes = test.getBytesRecibidos();
            this.enviadoAntes = test.getBytesEnviados();           
        }
        if(this.contador > 1){ 
            this.contador = 2;
            this.recibidoAntes = test.getBytesRecibidos();
            this.enviadoAntes = test.getBytesEnviados();           
            this.test.run();
                
            this.diferenciaRecibido = test.getBytesRecibidos()- this.recibidoAntes;
            this.diferenciaEnviado = test.getBytesEnviados()- this.enviadoAntes;
                
            this.throughputRecibido = (double)(diferenciaRecibido*8)/1000000;
            this.throughputEnviado = (double)(diferenciaEnviado*8)/1000000;           
        }      
        
        this.anchoBanda = (double)test.getAnchoBanda()/1000000;
        this.jLabelAnchoBanda.setText("Ancho de banda: "+round(this.anchoBanda,2)+" Mbps");
        this.gaugeRecibido.setMaxValue(this.anchoBanda);
        this.gaugeEnviado.setMaxValue(this.anchoBanda);
        this.gaugeRecibido.setValueAnimated(throughputRecibido);
        this.gaugeEnviado.setValueAnimated(throughputEnviado);
        
        if(this.throughputRecibido < 1){
            this.jLabelRecibido.setText("Recibido: "+round(throughputRecibido*1000, 2)+" Kbps");
        }else{
            this.jLabelRecibido.setText("Recibido: "+round(throughputRecibido, 2)+" Mbps");
        }
        
        if(this.throughputEnviado < 1){
            this.jLabelEnviado.setText("Enviado: "+round(throughputEnviado*1000, 2)+" Kbps");
        }else{
            this.jLabelEnviado.setText("Enviado: "+round(throughputEnviado, 2)+" Mbps");
        }    
        
    }
    
    //redondea un double a dos cifras decimales
    public static double round(double value, int places) {
        if (places < 0) throw new IllegalArgumentException();

        long factor = (long) Math.pow(10, places);
        value = value * factor;
        long tmp = Math.round(value);
        return (double) tmp / factor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonRegresar = new javax.swing.JButton();
        buttonSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelEnviado = new javax.swing.JLabel();
        jLabelRecibido = new javax.swing.JLabel();
        jLabelAnchoBanda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Throughtput de la red");

        buttonRegresar.setText("Regresar");
        buttonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegresarActionPerformed(evt);
            }
        });

        buttonSalir.setText("Salir");
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });

        jPanel2.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabelEnviado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelEnviado.setText("Enviado: 0.00 Kbps");

        jLabelRecibido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelRecibido.setText("Recibido: 0.00 Kbps");

        jLabelAnchoBanda.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelAnchoBanda.setText("Ancho de banda: 0.0 Mbps");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(buttonRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSalir)
                .addGap(223, 223, 223))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(95, 95, 95)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(171, 171, 171)
                            .addComponent(jLabelRecibido))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAnchoBanda)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelEnviado)
                        .addGap(170, 170, 170))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(jLabelAnchoBanda))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEnviado)
                    .addComponent(jLabelRecibido))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRegresar)
                    .addComponent(buttonSalir))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonSalirActionPerformed

    private void buttonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegresarActionPerformed
        this.dispose();
        this.ventanaInicio.setVisible(true);
    }//GEN-LAST:event_buttonRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRegresar;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAnchoBanda;
    private javax.swing.JLabel jLabelEnviado;
    private javax.swing.JLabel jLabelRecibido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
